
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 03 20:32:37 GMT 2007
//----------------------------------------------------

package thebeast.pml.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 66;
  public static final int DOUBLEDOT = 51;
  public static final int TIMES = 56;
  public static final int FROM = 14;
  public static final int CORPUS = 13;
  public static final int ARROW = 85;
  public static final int RCLPARENSTAR = 79;
  public static final int PREDICATE = 3;
  public static final int TYPE = 2;
  public static final int WEIGHTS = 26;
  public static final int INSPECT = 10;
  public static final int WEIGHT = 4;
  public static final int TEST = 36;
  public static final int SEMI = 46;
  public static final int LAMBDA = 93;
  public static final int GEQ = 61;
  public static final int SCORES = 24;
  public static final int UAND = 48;
  public static final int LOWERCASEID = 37;
  public static final int COMMA = 49;
  public static final int RPAREN = 73;
  public static final int CLEAR = 32;
  public static final int DOUBLE = 106;
  public static final int PUT = 99;
  public static final int JAVAID = 109;
  public static final int LPAREN = 72;
  public static final int RCLPARENEXCL = 83;
  public static final int ARG = 28;
  public static final int FALSE = 96;
  public static final int TILDE = 64;
  public static final int ACYCLIC = 23;
  public static final int NOTEQUALS = 58;
  public static final int BINS = 33;
  public static final int TYPES = 18;
  public static final int INTTYPE = 42;
  public static final int JUMP = 21;
  public static final int DOUBLEAND = 70;
  public static final int DOUBLEBAR = 71;
  public static final int WHEN = 89;
  public static final int DOLLAR = 94;
  public static final int INCLUDE = 40;
  public static final int NUMBER = 105;
  public static final int LESSTHAN = 59;
  public static final int TRUE = 95;
  public static final int PLUS = 54;
  public static final int WHILE = 102;
  public static final int ASSIGN = 50;
  public static final int ATOMS = 11;
  public static final int X = 5;
  public static final int DO = 103;
  public static final int FOR = 7;
  public static final int GREATER = 60;
  public static final int ARGIDENT = 110;
  public static final int ADD = 8;
  public static final int HIDDEN = 43;
  public static final int JAVA = 97;
  public static final int COLLECT = 27;
  public static final int RCLPAREN = 77;
  public static final int RSQPAREN = 75;
  public static final int EPOCHS = 30;
  public static final int DOT = 53;
  public static final int LOAD = 34;
  public static final int FACTOR = 22;
  public static final int MAP = 100;
  public static final int LCLPARENPLUS = 80;
  public static final int NULL = 104;
  public static final int EOF = 0;
  public static final int EQUIVALENCE = 67;
  public static final int FUNCTION = 87;
  public static final int PRINT = 15;
  public static final int INF = 39;
  public static final int UNDERSCORE = 9;
  public static final int GOLD = 12;
  public static final int LCLPARENSTAR = 78;
  public static final int LSQPAREN = 74;
  public static final int MINUS = 55;
  public static final int SOLVE = 16;
  public static final int LEARN = 17;
  public static final int IN = 91;
  public static final int IDENT = 107;
  public static final int SET = 31;
  public static final int error = 1;
  public static final int EXCL = 63;
  public static final int SEQ = 29;
  public static final int IF = 6;
  public static final int OF = 92;
  public static final int SAVE = 35;
  public static final int LCLPAREN = 76;
  public static final int DOUBLETYPE = 41;
  public static final int ASSERT = 90;
  public static final int COLON = 52;
  public static final int GREEDY = 25;
  public static final int DOUBLESEMI = 45;
  public static final int UPPERCASEID = 38;
  public static final int LCLPARENEXCL = 82;
  public static final int STRING = 108;
  public static final int CURLYARROW = 86;
  public static final int OBSERVED = 44;
  public static final int AND = 68;
  public static final int BAR = 84;
  public static final int TO = 19;
  public static final int IMPLIES = 69;
  public static final int ELLIPSIS = 20;
  public static final int UMINUS = 47;
  public static final int WITH = 101;
  public static final int LET = 88;
  public static final int RCLPARENPLUS = 81;
  public static final int INVERT = 98;
  public static final int EQUALS = 57;
  public static final int LEQ = 62;
  public static final int HASH = 65;
}

