
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 22 20:18:01 GMT 2007
//----------------------------------------------------

package thebeast.pml.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 63;
  public static final int DOUBLEDOT = 48;
  public static final int TIMES = 53;
  public static final int FROM = 14;
  public static final int CORPUS = 13;
  public static final int ARROW = 82;
  public static final int RCLPARENSTAR = 76;
  public static final int PREDICATE = 3;
  public static final int TYPE = 2;
  public static final int WEIGHTS = 26;
  public static final int INSPECT = 10;
  public static final int WEIGHT = 4;
  public static final int SEMI = 43;
  public static final int LAMBDA = 90;
  public static final int GEQ = 58;
  public static final int SCORES = 24;
  public static final int UAND = 45;
  public static final int LOWERCASEID = 34;
  public static final int COMMA = 46;
  public static final int RPAREN = 70;
  public static final int CLEAR = 32;
  public static final int DOUBLE = 103;
  public static final int PUT = 96;
  public static final int JAVAID = 106;
  public static final int LPAREN = 69;
  public static final int RCLPARENEXCL = 80;
  public static final int ARG = 28;
  public static final int FALSE = 93;
  public static final int TILDE = 61;
  public static final int ACYCLIC = 23;
  public static final int NOTEQUALS = 55;
  public static final int BINS = 33;
  public static final int TYPES = 18;
  public static final int INTTYPE = 39;
  public static final int JUMP = 21;
  public static final int DOUBLEAND = 67;
  public static final int DOUBLEBAR = 68;
  public static final int WHEN = 86;
  public static final int DOLLAR = 91;
  public static final int INCLUDE = 37;
  public static final int NUMBER = 102;
  public static final int LESSTHAN = 56;
  public static final int TRUE = 92;
  public static final int PLUS = 51;
  public static final int WHILE = 99;
  public static final int ASSIGN = 47;
  public static final int ATOMS = 11;
  public static final int X = 5;
  public static final int DO = 100;
  public static final int FOR = 7;
  public static final int GREATER = 57;
  public static final int ARGIDENT = 107;
  public static final int ADD = 8;
  public static final int HIDDEN = 40;
  public static final int JAVA = 94;
  public static final int COLLECT = 27;
  public static final int RCLPAREN = 74;
  public static final int RSQPAREN = 72;
  public static final int EPOCHS = 30;
  public static final int DOT = 50;
  public static final int FACTOR = 22;
  public static final int MAP = 97;
  public static final int LCLPARENPLUS = 77;
  public static final int NULL = 101;
  public static final int EOF = 0;
  public static final int EQUIVALENCE = 64;
  public static final int FUNCTION = 84;
  public static final int PRINT = 15;
  public static final int INF = 36;
  public static final int UNDERSCORE = 9;
  public static final int GOLD = 12;
  public static final int LCLPARENSTAR = 75;
  public static final int LSQPAREN = 71;
  public static final int MINUS = 52;
  public static final int SOLVE = 16;
  public static final int LEARN = 17;
  public static final int IN = 88;
  public static final int IDENT = 104;
  public static final int SET = 31;
  public static final int error = 1;
  public static final int EXCL = 60;
  public static final int SEQ = 29;
  public static final int IF = 6;
  public static final int OF = 89;
  public static final int LCLPAREN = 73;
  public static final int DOUBLETYPE = 38;
  public static final int ASSERT = 87;
  public static final int COLON = 49;
  public static final int GREEDY = 25;
  public static final int DOUBLESEMI = 42;
  public static final int UPPERCASEID = 35;
  public static final int LCLPARENEXCL = 79;
  public static final int STRING = 105;
  public static final int CURLYARROW = 83;
  public static final int OBSERVED = 41;
  public static final int AND = 65;
  public static final int BAR = 81;
  public static final int TO = 19;
  public static final int IMPLIES = 66;
  public static final int ELLIPSIS = 20;
  public static final int UMINUS = 44;
  public static final int WITH = 98;
  public static final int LET = 85;
  public static final int RCLPARENPLUS = 78;
  public static final int INVERT = 95;
  public static final int EQUALS = 54;
  public static final int LEQ = 59;
  public static final int HASH = 62;
}

