#!/bin/bash
WORKING_DIR=models
TEMPLATE_DIR=../template
ITERS=5
TYPES="../data/conll05/train_propbank.types.pml"
ATOMS="../data/conll05/train_propbank.atoms"
ATOMS_TEST="../data/conll05/devel_propbank.atoms"
ATOMS_RES="../results/devel_propbank.open"
MODEL="model1_nopredicate.pml"
MODEL_DIR="../results/model"
INSTANCES="/disk/home/dendrite/s0349492/ivan/eacl_probank.dmp"
WEIGHTS="/disk/home/dendrite/s0349492/ivan/eacl_probank.PROID.weights"
TEMPLATE_INI="init.pml"
TEMPLATE_LEARN="learn.pml"
TEMPLATE_TEST="test.pml"
MODE=3
ATOM_TESTS=../data/conll05/test_wsj_propbank::../data/conll05/test_brown_propbank


if [ $# -gt 0 ]
then
    MODE=$1
fi

if [ $# -gt 1 ]
then
    ITERS=$2
fi

if [ $# -gt 2 ]
then
    ID=$3
fi


if [ $# -gt 3 ]
then
    echo -n $USAGE
    exit 1;
fi

set -x
scripts/run_train_test2 $WORKING_DIR $TEMPLATE_DIR $ITERS $TYPES $ATOMS\
        $ATOMS_TEST $ATOMS_RES $MODEL $MODEL_DIR $INSTANCES $WEIGHTS $TEMPLATE_INI\
        $TEMPLATE_LEARN $TEMPLATE_TEST $MODE ${ATOMS_TESTS} $ID

