#!/bin/bash

# Generates the files were the possiblePredicate is true when the word is a SRL predicate 

USAGE="
    Usage: tranlatecorpora2conll08 [options]]\n
    -a      No ask for confirmation\n
    -help   Print this"

opts=" -v --possible_ON "

if [ $# -gt 1 ]
then
    echo -n $USAGE
    exit 1;
fi

CONFIRM=1
if [ $# -eq 1 ]
then
    case $1 in
        "-a"     ) CONFIRM=0;;
        *        ) echo -e $USAGE;exit 1;;
    esac 
fi

# Commandline to transform conll08 corpus into the beast corpus
echo "
creates the following corpora:
 devel.closed -> devel_propbank.closed.atoms & devel_propbank.closed.types.pml
 train.closed -> train_propbank.closed.atoms & train_propbank.closed.types.pml
"

# Conll05

if [ $CONFIRM -eq 0 ]
then
    ANS="yes"
else
    echo -n "translate conll05 close devel ? (yes/[no]) "
    read -e ANS
fi

if [ -z $ANS ]
then
    ANS="no"
fi

if [ $ANS = "yes" ]
then
    set -x
    nice bin/conll082beast.py ${opts} -d data/conll05/devel_propbank.types.pml -o data/conll05/devel_propbank.atoms -M /disk/home/dendrite/s0349492/conll08/depparse/devel.closed.conll.out data/conll05/devel_propbank.output
    set +x
fi


if [ $CONFIRM -eq 0 ]
then
    ANS="yes"
else
    echo -n "translate conll05 close trian ? (yes/[no]) "
    read -e ANS
fi

if [ -z $ANS ]
then
    ANS="no"
fi

if [  $ANS = "yes" ]
then
    set -x
    nice bin/conll082beast.py ${opts} -d data/conll05/train_propbank.types.pml -o data/conll05/train_propbank.atoms -M data/mst_fixed/depparse.3fold.test.0.conll.out@data/mst_fixed/depparse.3fold.test.1.conll.out@data/mst_fixed/depparse.3fold.test.2.conll.out data/conll05/train_propbank.output
    set +x
fi


if [ $CONFIRM -eq 0 ]
then
    ANS="yes"
else
    echo -n "translate open test.wsj ? (yes/[no]) "
    read -e ANS
fi

if [ -z $ANS ]
then
    ANS="no"
fi

if [ $ANS = "yes" ]
then
    set -x
    nice bin/conll082beast.py ${opts} -T -O data/test.wsj/test.wsj.open -d data/test.wsj/test.wsj.open.types.pml -o data/test.wsj/test.wsj.open.atoms   data/test.wsj/test.wsj.closed
    set +x
fi


if [ $CONFIRM -eq 0 ]
then
    ANS="yes"
else
    echo -n "translate open test.brown ? (yes/[no]) "
    read -e ANS
fi

if [ -z $ANS ]
then
    ANS="no"
fi

if [ $ANS = "yes" ]
then
    set -x
    nice bin/conll082beast.py ${opts} -T -O data/test.brown/test.brown.open -d data/test.brown/test.brown.open.types.pml -o data/test.brown/test.brown.open.atoms   data/test.brown/test.brown.closed
    set +x
fi

