
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 10 22:54:58 GMT 2007
//----------------------------------------------------

package thebeast.pml.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 68;
  public static final int DOUBLEDOT = 53;
  public static final int TIMES = 58;
  public static final int FROM = 14;
  public static final int CORPUS = 13;
  public static final int ARROW = 87;
  public static final int RCLPARENSTAR = 81;
  public static final int PREDICATE = 3;
  public static final int TYPE = 2;
  public static final int WEIGHTS = 26;
  public static final int INSPECT = 10;
  public static final int WEIGHT = 4;
  public static final int TEST = 36;
  public static final int SEMI = 48;
  public static final int LAMBDA = 95;
  public static final int GEQ = 63;
  public static final int SCORES = 24;
  public static final int UAND = 50;
  public static final int LOWERCASEID = 39;
  public static final int COMMA = 51;
  public static final int RPAREN = 75;
  public static final int CLEAR = 32;
  public static final int DOUBLE = 108;
  public static final int PUT = 101;
  public static final int JAVAID = 111;
  public static final int LPAREN = 74;
  public static final int RCLPARENEXCL = 85;
  public static final int ARG = 28;
  public static final int FALSE = 98;
  public static final int TILDE = 66;
  public static final int ACYCLIC = 23;
  public static final int NOTEQUALS = 60;
  public static final int BINS = 33;
  public static final int TYPES = 18;
  public static final int INTTYPE = 44;
  public static final int JUMP = 21;
  public static final int DOUBLEAND = 72;
  public static final int DOUBLEBAR = 73;
  public static final int WHEN = 91;
  public static final int DOLLAR = 96;
  public static final int INCLUDE = 42;
  public static final int NUMBER = 107;
  public static final int LESSTHAN = 61;
  public static final int TRUE = 97;
  public static final int PLUS = 56;
  public static final int INDEX = 37;
  public static final int WHILE = 104;
  public static final int ASSIGN = 52;
  public static final int ATOMS = 11;
  public static final int X = 5;
  public static final int DO = 105;
  public static final int FOR = 7;
  public static final int GREATER = 62;
  public static final int ARGIDENT = 112;
  public static final int ADD = 8;
  public static final int HIDDEN = 45;
  public static final int JAVA = 99;
  public static final int COLLECT = 27;
  public static final int RCLPAREN = 79;
  public static final int RSQPAREN = 77;
  public static final int EPOCHS = 30;
  public static final int DOT = 55;
  public static final int LOAD = 34;
  public static final int FACTOR = 22;
  public static final int MAP = 102;
  public static final int LCLPARENPLUS = 82;
  public static final int NULL = 106;
  public static final int EOF = 0;
  public static final int EQUIVALENCE = 69;
  public static final int FUNCTION = 89;
  public static final int PRINT = 15;
  public static final int INF = 41;
  public static final int UNDERSCORE = 9;
  public static final int GOLD = 12;
  public static final int LCLPARENSTAR = 80;
  public static final int LSQPAREN = 76;
  public static final int MINUS = 57;
  public static final int SOLVE = 16;
  public static final int LEARN = 17;
  public static final int IN = 93;
  public static final int IDENT = 109;
  public static final int SET = 31;
  public static final int error = 1;
  public static final int EXCL = 65;
  public static final int SEQ = 29;
  public static final int IF = 6;
  public static final int OF = 94;
  public static final int SAVE = 35;
  public static final int LCLPAREN = 78;
  public static final int DOUBLETYPE = 43;
  public static final int ASSERT = 92;
  public static final int COLON = 54;
  public static final int GREEDY = 25;
  public static final int GLOBAL = 38;
  public static final int DOUBLESEMI = 47;
  public static final int UPPERCASEID = 40;
  public static final int LCLPARENEXCL = 84;
  public static final int STRING = 110;
  public static final int CURLYARROW = 88;
  public static final int OBSERVED = 46;
  public static final int AND = 70;
  public static final int BAR = 86;
  public static final int IMPLIES = 71;
  public static final int TO = 19;
  public static final int ELLIPSIS = 20;
  public static final int UMINUS = 49;
  public static final int WITH = 103;
  public static final int LET = 90;
  public static final int RCLPARENPLUS = 83;
  public static final int INVERT = 100;
  public static final int EQUALS = 59;
  public static final int LEQ = 64;
  public static final int HASH = 67;
}

