
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 09 04:41:43 BST 2007
//----------------------------------------------------

package thebeast.pml.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 70;
  public static final int DOUBLEDOT = 54;
  public static final int TIMES = 59;
  public static final int FROM = 14;
  public static final int CORPUS = 13;
  public static final int ARROW = 89;
  public static final int RCLPARENSTAR = 83;
  public static final int PREDICATE = 3;
  public static final int TYPE = 2;
  public static final int WEIGHTS = 26;
  public static final int INSPECT = 10;
  public static final int WEIGHT = 4;
  public static final int TEST = 36;
  public static final int SEMI = 49;
  public static final int LAMBDA = 97;
  public static final int GEQ = 64;
  public static final int SCORES = 24;
  public static final int UAND = 51;
  public static final int LOWERCASEID = 40;
  public static final int COMMA = 52;
  public static final int RPAREN = 77;
  public static final int CLEAR = 32;
  public static final int DOUBLE = 110;
  public static final int PUT = 103;
  public static final int JAVAID = 113;
  public static final int LPAREN = 76;
  public static final int RCLPARENEXCL = 87;
  public static final int ARG = 28;
  public static final int FALSE = 100;
  public static final int TILDE = 68;
  public static final int ACYCLIC = 23;
  public static final int NOTEQUALS = 61;
  public static final int BINS = 33;
  public static final int TYPES = 18;
  public static final int INTTYPE = 45;
  public static final int JUMP = 21;
  public static final int DOUBLEAND = 74;
  public static final int DOUBLEBAR = 75;
  public static final int WHEN = 93;
  public static final int DOLLAR = 98;
  public static final int INCLUDE = 43;
  public static final int NUMBER = 109;
  public static final int LESSTHAN = 62;
  public static final int TRUE = 99;
  public static final int PLUS = 57;
  public static final int INDEX = 37;
  public static final int WHILE = 106;
  public static final int ASSIGN = 53;
  public static final int ATOMS = 11;
  public static final int X = 5;
  public static final int DO = 107;
  public static final int FOR = 7;
  public static final int GREATER = 63;
  public static final int ARGIDENT = 114;
  public static final int ADD = 8;
  public static final int HIDDEN = 46;
  public static final int JAVA = 101;
  public static final int GEQCLOSURE = 65;
  public static final int COLLECT = 27;
  public static final int RCLPAREN = 81;
  public static final int RSQPAREN = 79;
  public static final int EPOCHS = 30;
  public static final int DOT = 56;
  public static final int LOAD = 34;
  public static final int FACTOR = 22;
  public static final int MAP = 104;
  public static final int LCLPARENPLUS = 84;
  public static final int NULL = 108;
  public static final int EOF = 0;
  public static final int EQUIVALENCE = 71;
  public static final int FUNCTION = 91;
  public static final int PRINT = 15;
  public static final int INF = 42;
  public static final int UNDERSCORE = 9;
  public static final int GOLD = 12;
  public static final int LCLPARENSTAR = 82;
  public static final int LSQPAREN = 78;
  public static final int MINUS = 58;
  public static final int SOLVE = 16;
  public static final int LEARN = 17;
  public static final int IN = 95;
  public static final int IDENT = 111;
  public static final int SET = 31;
  public static final int error = 1;
  public static final int EXCL = 67;
  public static final int SEQ = 29;
  public static final int IF = 6;
  public static final int OF = 96;
  public static final int SAVE = 35;
  public static final int ESCAPEQUOTE = 39;
  public static final int LCLPAREN = 80;
  public static final int DOUBLETYPE = 44;
  public static final int ASSERT = 94;
  public static final int COLON = 55;
  public static final int GREEDY = 25;
  public static final int GLOBAL = 38;
  public static final int DOUBLESEMI = 48;
  public static final int UPPERCASEID = 41;
  public static final int LCLPARENEXCL = 86;
  public static final int STRING = 112;
  public static final int CURLYARROW = 90;
  public static final int AND = 72;
  public static final int OBSERVED = 47;
  public static final int BAR = 88;
  public static final int IMPLIES = 73;
  public static final int TO = 19;
  public static final int ELLIPSIS = 20;
  public static final int UMINUS = 50;
  public static final int WITH = 105;
  public static final int LET = 92;
  public static final int RCLPARENPLUS = 85;
  public static final int INVERT = 102;
  public static final int EQUALS = 60;
  public static final int LEQ = 66;
  public static final int HASH = 69;
}

