/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thebeast_osi_CbcModel */

#ifndef _Included_thebeast_osi_CbcModel
#define _Included_thebeast_osi_CbcModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thebeast_osi_CbcModel
 * Method:    createCbcModel
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_thebeast_osi_CbcModel_createCbcModel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    branchAndBound
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_branchAndBound
  (JNIEnv *, jobject, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    solver
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_thebeast_osi_CbcModel_solver
  (JNIEnv *, jclass, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    referenceSolver
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_thebeast_osi_CbcModel_referenceSolver
  (JNIEnv *, jclass, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    saveReferenceSolver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_saveReferenceSolver
  (JNIEnv *, jclass, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    resetToReferenceSolver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_resetToReferenceSolver
  (JNIEnv *, jclass, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    bestSolution
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_thebeast_osi_CbcModel_bestSolution
  (JNIEnv *, jobject, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    setMaximumSeconds
 * Signature: (DJ)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_setMaximumSeconds
  (JNIEnv *, jobject, jdouble, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    setLogLevel
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_setLogLevel
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    addCglProbing
 * Signature: (ZIIIIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_addCglProbing
  (JNIEnv *, jobject, jboolean, jint, jint, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    addCglGomory
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_addCglGomory
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    addCglKnapsackCover
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_addCglKnapsackCover
  (JNIEnv *, jobject, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    addCglRedsplit
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_addCglRedsplit
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    addCglClique
 * Signature: (ZZJ)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_addCglClique
  (JNIEnv *, jobject, jboolean, jboolean, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    addCglMixedIntegerRounding2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_addCglMixedIntegerRounding2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    addCglFlowCover
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_CbcModel_addCglFlowCover
  (JNIEnv *, jobject, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    setAllowableGap
 * Signature: (DJ)Z
 */
JNIEXPORT jboolean JNICALL Java_thebeast_osi_CbcModel_setAllowableGap
  (JNIEnv *, jobject, jdouble, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    setAllowableFractionGap
 * Signature: (DJ)Z
 */
JNIEXPORT jboolean JNICALL Java_thebeast_osi_CbcModel_setAllowableFractionGap
  (JNIEnv *, jobject, jdouble, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    setAllowablePercentageGap
 * Signature: (DJ)Z
 */
JNIEXPORT jboolean JNICALL Java_thebeast_osi_CbcModel_setAllowablePercentageGap
  (JNIEnv *, jobject, jdouble, jlong);

/*
 * Class:     thebeast_osi_CbcModel
 * Method:    setMaximumNodes
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_thebeast_osi_CbcModel_setMaximumNodes
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
