/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thebeast_osi_OsiSolverJNI_Implementation */

#ifndef _Included_thebeast_osi_OsiSolverJNI_Implementation
#define _Included_thebeast_osi_OsiSolverJNI_Implementation
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
