/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thebeast_osi_OsiSolverJNI */

#ifndef _Included_thebeast_osi_OsiSolverJNI
#define _Included_thebeast_osi_OsiSolverJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    createImplementation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_thebeast_osi_OsiSolverJNI_createImplementation
  (JNIEnv *, jclass, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    setHintParam
 * Signature: (IZII)Z
 */
JNIEXPORT jboolean JNICALL Java_thebeast_osi_OsiSolverJNI_setHintParam
  (JNIEnv *, jclass, jint, jboolean, jint, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    initialSolve
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_initialSolve
  (JNIEnv *, jobject, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    resolve
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_resolve
  (JNIEnv *, jobject, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    branchAndBound
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_branchAndBound
  (JNIEnv *, jobject, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    getNumCols
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_thebeast_osi_OsiSolverJNI_getNumCols
  (JNIEnv *, jobject, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    setCbcLogLevel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_setCbcLogLevel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    getNumRows
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_thebeast_osi_OsiSolverJNI_getNumRows
  (JNIEnv *, jobject, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    getColSolution
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_thebeast_osi_OsiSolverJNI_getColSolution
  (JNIEnv *, jobject, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    setColLower
 * Signature: (IDI)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_setColLower
  (JNIEnv *, jobject, jint, jdouble, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    setColUpper
 * Signature: (IDI)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_setColUpper
  (JNIEnv *, jobject, jint, jdouble, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    setObjCooeff
 * Signature: (IDI)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_setObjCooeff
  (JNIEnv *, jobject, jint, jdouble, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    addCol
 * Signature: (I[I[DDDDI)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_addCol
  (JNIEnv *, jobject, jint, jintArray, jdoubleArray, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    addRow
 * Signature: (I[I[DDDI)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_addRow
  (JNIEnv *, jobject, jint, jintArray, jdoubleArray, jdouble, jdouble, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    reset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    delete
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_delete
  (JNIEnv *, jobject, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    getObjValue
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_thebeast_osi_OsiSolverJNI_getObjValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    setObjSense
 * Signature: (DI)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_setObjSense
  (JNIEnv *, jobject, jdouble, jint);

/*
 * Class:     thebeast_osi_OsiSolverJNI
 * Method:    setInteger
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_thebeast_osi_OsiSolverJNI_setInteger
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
